# Copyright 2024 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Auto-Generated by cargo-ebuild 0.5.4-r1

EAPI=8

CRATES="
	aho-corasick@1.0.5
	anstream@0.3.2
	anstream@0.5.0
	anstyle@1.0.2
	anstyle-parse@0.2.1
	anstyle-query@1.0.0
	anstyle-wincon@1.0.2
	anstyle-wincon@2.1.0
	assert_cmd@2.0.12
	autocfg@1.1.0
	bitflags@1.3.2
	bitflags@2.4.0
	bstr@1.6.2
	cc@1.0.83
	cfg-if@1.0.0
	clap@4.4.2
	clap_builder@4.4.2
	clap_derive@4.4.2
	clap_lex@0.5.1
	codespan-reporting@0.11.1
	colorchoice@1.0.0
	const_format@0.2.31
	const_format_proc_macros@0.2.31
	crossterm@0.25.0
	crossterm_winapi@0.9.1
	deranged@0.3.8
	difflib@0.4.0
	doc-comment@0.3.3
	dyn-clone@1.0.13
	either@1.9.0
	equivalent@1.0.1
	errno@0.3.3
	errno-dragonfly@0.1.2
	extend@1.2.0
	float-cmp@0.9.0
	hashbrown@0.14.0
	heck@0.4.1
	hermit-abi@0.3.2
	indexmap@2.0.0
	inquire@0.6.2
	is-terminal@0.4.9
	is_debug@1.0.1
	itertools@0.10.5
	itertools@0.11.0
	itoa@1.0.9
	lazy_static@1.4.0
	libc@0.2.147
	linux-raw-sys@0.4.5
	lock_api@0.4.10
	log@0.4.20
	memchr@2.6.3
	mio@0.8.8
	newline-converter@0.2.2
	noodler@0.1.0
	normalize-line-endings@0.3.0
	nu-ansi-term@0.46.0
	nu-ansi-term@0.49.0
	num-traits@0.2.16
	num_threads@0.1.6
	once_cell@1.18.0
	overload@0.1.1
	parking_lot@0.12.1
	parking_lot_core@0.9.8
	pin-project-lite@0.2.13
	predicates@3.0.3
	predicates-core@1.0.6
	predicates-tree@1.0.9
	proc-macro2@1.0.66
	quote@1.0.33
	redox_syscall@0.3.5
	regex@1.9.5
	regex-automata@0.3.8
	regex-syntax@0.7.5
	rustix@0.38.11
	ryu@1.0.15
	same-file@1.0.6
	scopeguard@1.2.0
	serde@1.0.188
	serde_derive@1.0.188
	serde_json@1.0.105
	shadow-rs@0.23.0
	sharded-slab@0.1.4
	signal-hook@0.3.17
	signal-hook-mio@0.2.3
	signal-hook-registry@1.4.1
	smallvec@1.11.0
	strip-ansi-escapes@0.2.0
	strsim@0.10.0
	syn@1.0.109
	syn@2.0.31
	termcolor@1.2.0
	termtree@0.4.1
	thisctx@0.4.0
	thisctx_impl@0.4.0
	thiserror@1.0.48
	thiserror-impl@1.0.48
	thread_local@1.1.7
	time@0.3.28
	time-core@0.1.1
	time-macros@0.2.14
	tracing@0.1.37
	tracing-attributes@0.1.26
	tracing-core@0.1.31
	tracing-log@0.1.3
	tracing-subscriber@0.3.17
	unicode-ident@1.0.11
	unicode-segmentation@1.10.1
	unicode-width@0.1.10
	unicode-xid@0.2.4
	utf8parse@0.2.1
	valuable@0.1.0
	vte@0.11.1
	vte_generate_state_changes@0.1.1
	wait-timeout@0.2.0
	walkdir@2.3.3
	wasi@0.11.0+wasi-snapshot-preview1
	winapi@0.3.9
	winapi-i686-pc-windows-gnu@0.4.0
	winapi-util@0.1.5
	winapi-x86_64-pc-windows-gnu@0.4.0
	windows-sys@0.48.0
	windows-targets@0.48.5
	windows_aarch64_gnullvm@0.48.5
	windows_aarch64_msvc@0.48.5
	windows_i686_gnu@0.48.5
	windows_i686_msvc@0.48.5
	windows_x86_64_gnu@0.48.5
	windows_x86_64_gnullvm@0.48.5
	windows_x86_64_msvc@0.48.5
"

inherit cargo

DESCRIPTION="Helps you to find/fix obsolete Nerd Font icons in your project"
# Double check the homepage as the cargo_metadata crate
# does not provide this value so instead repository is used
HOMEPAGE="https://github.com/loichyan/nerdfix"
SRC_URI="https://github.com/loichyan/${PN}/archive/refs/tags/v${PV}.tar.gz -> ${P}.tar.gz
	${CARGO_CRATE_URIS}"

# License set may be more restrictive as OR is not respected
# use cargo-license for a more accurate license picture
LICENSE="Apache-2.0 MIT ZLIB"
SLOT="0"
KEYWORDS="~amd64"

# rust does not use *FLAGS from make.conf, silence portage warning
# update with proper path to binaries this crate installs, omit leading /
QA_FLAGS_IGNORED="usr/bin/${PN}"
