# Copyright 1999-2014 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.16.5

EAPI=5

MODULE_AUTHOR="RRWO"
MODULE_VERSION="v1.1.2"


inherit perl-module

DESCRIPTION="Convert Module POD to a README file"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="alpha amd64 amd64-fbsd arm arm64 hppa ia64 m68k mips ppc ppc64 s390 sh sparc sparc-fbsd x86 x86-fbsd   ppc-aix x86-freebsd x64-freebsd sparc64-freebsd hppa-hpux ia64-hpux x86-interix amd64-linux arm-linux ia64-linux ppc64-linux x86-linux ppc-macos x86-macos x64-macos m68k-mint x86-netbsd ppc-openbsd x86-openbsd x64-openbsd sparc-solaris sparc64-solaris x64-solaris x86-solaris x86-winnt x86-cygwin"
IUSE=""

DEPEND="dev-perl/Path-Tiny
	dev-perl/Moo
	dev-perl/Try-Tiny
	dev-perl/Pod-Simple-LaTeX
	dev-perl/Type-Tiny
	dev-perl/Getopt-Long-Descriptive
	dev-perl/File-Slurp
	dev-perl/Pod-Markdown
	>=dev-perl/CPAN-Changes-0.270.0
	dev-perl/Test-Exception
	dev-perl/Type-Tiny-XS
	dev-perl/Role-Tiny
	dev-perl/IO-String
	dev-perl/Test-Deep
	dev-perl/MooX-HandlesVia
	dev-perl/namespace-autoclean
	>=dev-perl/Class-Method-Modifiers-2.30.0
	dev-lang/perl"
