#!/bin/sh
PATH=/sbin:/usr/sbin:/bin:/usr/bin

RUNLEVEL=S /sbin/rc sysinit
RUNLEVEL=S /sbin/rc boot

# Set default action (shutdown or not) if Ctrl+Alt+Del pressed,
# but /etc/runit/ctrlaltdel don't setup /etc/runit/stopit.
touch /etc/runit/stopit
chmod 100 /etc/runit/stopit

# Set default action on shutdown (halt or reboot) if:
# - /etc/runit/1 crash or exit 100
# - /etc/runit/2 exit non 111
# - Ctrl+Alt+Del pressed, but /etc/runit/ctrlaltdel don't setup /etc/runit/reboot
touch /etc/runit/reboot
chmod 100 /etc/runit/reboot
    
