#!/bin/sh
PATH=/bin:/usr/bin

# Select action on shutdown: reboot or halt
touch /etc/runit/reboot
chmod 100 /etc/runit/reboot

# Select action: shutdown or not
touch /etc/runit/stopit
chmod 100 /etc/runit/stopit

echo "System is going down in 14 seconds..." | wall
/bin/sleep 14

