# Copyright 1999-2014 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.16.5

EAPI=5

MODULE_AUTHOR="CJM"
MODULE_VERSION="2.029"


inherit perl-module

DESCRIPTION="update your git repository after release"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="alpha amd64 amd64-fbsd arm arm64 hppa ia64 m68k mips ppc ppc64 s390 sh sparc sparc-fbsd x86 x86-fbsd   ppc-aix x86-freebsd x64-freebsd sparc64-freebsd hppa-hpux ia64-hpux x86-interix amd64-linux arm-linux ia64-linux ppc64-linux x86-linux ppc-macos x86-macos x64-macos m68k-mint x86-netbsd ppc-openbsd x86-openbsd x64-openbsd sparc-solaris sparc64-solaris x64-solaris x86-solaris x86-winnt x86-cygwin"
IUSE=""

DEPEND="dev-perl/Dist-Zilla
	dev-perl/Try-Tiny
	dev-perl/IPC-System-Simple
	dev-perl/MooseX-Types
	dev-perl/File-Copy-Recursive
	dev-perl/Moose
	dev-perl/String-Formatter
	dev-perl/File-Which
	dev-perl/File-chdir
	dev-perl/Dist-Zilla-Plugin-Config-Git
	dev-perl/DateTime
	dev-perl/Version-Next
	>=dev-perl/Git-Wrapper-0.17.0
	dev-perl/Module-Runtime
	dev-perl/Devel-SimpleTrace
	>=dev-perl/namespace-autoclean-0.130.0
	dev-perl/List-AllUtils
	>=dev-perl/Path-Tiny-0.48
	>=dev-perl/MooseX-Types-Path-Tiny-0.2.0
	dev-perl/MooseX-Has-Sugar
	dev-perl/Log-Dispatchouli
	>=dev-perl/Test-Fatal-0.10.0
	dev-perl/File-pushd
	dev-perl/List-MoreUtils
	>=dev-perl/CPAN-Meta-Check-0.4.0
	dev-lang/perl"
SRC_TEST="do"
